### PR TITLE
update token.json cedi digital

### PR DESCRIPTION
**Pull request by zfuturetech**
update - cedi digital

### CODE REVIEW

**Comment by webeli** [comment]
- Why is the ticker named `GHSÞ` when the token is called `cedi digital`.
- Where do you have liquidity?

**Comment by webeli** [comment]
Closing please reopen with updates on previous questions.

**Comment by zfuturetech** [comment]
> * Why is the ticker named `GHSÞ` when the token is called `cedi digital`.
> * Where do you have liquidity?

*The ticker has an ascii symbol (Thorn) which is a play on ¢. GHS is a currency ticker like USD. The thorn distinguishes the token while GHSÞ suggests it's peg (Cedi) same as flexUSD suggests a peg.

*Liquidity on Benswap

**Comment by webeli** [comment]
No update, closing.

**Comment by zfuturetech** [comment]
Ticker to GHS will clash with the ticker of the underlying asset which has the GHS ticker. Think of our ticker like USDt. The thorn symbol Þ which also looks like a miniature D serves to differentiate.

Liquidity is at Benswap but primarily FlexUSD which serves as our version of the GHS/USD pair.

https://dex.benswap.cash/#/swap?inputCurrency=0x0f207C9A5De76219D0979D6a8D0d07287E265974&outputCurrency=0x7b2B3C5308ab5b2a1d9a94d20D35CCDf61e05b72

------- Original Message -------

**Pull request closed without merging**
