### PR TITLE
added 1bch.com tokens

### PR DESCRIPTION
**Pull request by 1BCHDev1**
added 1bch.com tokens

### CODE REVIEW

**Comment by webeli** [comment]
Please provide further information:

- Who's running this DEX? Anon/Doxxed?
- Why is there two tokens?
- Is there an SDK we can use to pull data?
- Timelock?
- Migrator code?
- Audits?

Broken link when clicking learn on rBCH: https://docs-dex.1bch.com/tokenomics/cake/

We've decided to be more careful when adding new DEXes from unknowns (after the Beachswap situation). Will see how things pan out before adding this.

**Comment by 1BCHDev1** [comment]
Hello.

Sorry we didn't see the requirements for DEX listing. Gladly we communicate more details:

- our DEX founder is Eric who has a long standing in the BCH community https://www.reddit.com/user/MobTwo/
- there are 2 tokens because 1BCH is the main token for some popular pairs and has well-defined tokenomics such as 250 mio limited supply. While rBCH is our reward token = farming token you receive for providing LP or you can stake it in sprinklers to receive smaller coins.
- There is a migrator code and 6 day timelock when moving calling it
- We are planning to do an audit, however it has not been completed yet at launch. You can find our contracts at https://github.com/1bch/1BCH-DEx-Contracts

We fixed the broken links, 24h within launch was a a lot of hurry, sorry for this.

**Comment by 1BCHDev1** [comment]
You can find our DeFiLama adapter here in case you need to access DEX TLV features: https://github.com/1bch/DefiLlama-Adapters/blob/main/projects/1bch/index.js

Not sure what else you need from an SDK for a token listing? But we gladly provide it afterwards if you want to integrate our DEX deeper.

**Comment by 1BCHDev1** [comment]
Here is our full SDK https://github.com/1bch/1bch-dex-swap-sdk

**Comment by webeli** [comment]
@1BCHDev1 thank you, will start implement 1BCH SDK to marketcap.cash today/tomorrow.

**Comment by webeli** [comment]
@1BCHDev1 in the meantime please rebase/update this PR to latest on main branch so i can merge it.

**Comment by 1BCHDev1** [comment]
done. All up2date

**Pull request closed without merging**
