### PR TITLE
Add "The One" RULE token

### LINKED ISSUE #142: The One: RULE
{
  "name": "The One",
  "desc": "The One to Rule them all. Ownership renounced. All added to liquidity. All LP tokens have been burned. Now You Rule.",
  "address": "0x4780a76CDbB16bd0A4603e1e9a2dDAB7E7f9659E",
  "symbol": "RULE",
  "image": "https://user-images.githubusercontent.com/78986433/149631871-29f65afe-ab15-456e-a65c-a32a929a68b7.png",
  "websites": ["http://rule.cash/"],
  "telegram": "https://t.me/RULEToken",
  "twitter": "...",
  "discord": "https://discord.gg/fATz49V",
  "github": "..."
}
Pull request #130 
Liquidity is on tropical, is over 0.5 BCH https://www.smartscan.cash/address/0xeafaa9dfebf22faa88fd634701a249b23359094e

### PR DESCRIPTION
**Pull request by GiverofMemory**
Updated 1/15/22, closes #142 

{ “Name” - “The One”
“Project Description” - “The One to Rule them all. Ownership renounced. All added to liquidity. All LP tokens have been burned. Now You Rule.”
“Contract” - “0x4780a76CDbB16bd0A4603e1e9a2dDAB7E7f9659E”
“Symbol” - “RULE”
“Website” - ["http://rule.cash/"]
“Telegram” - “https://t.me/RULEToken”
“Twitter” - “None”
"Discord" - "https://discord.gg/fATz49V"
“Which DEX is your liquidity on” - “Tropical”
“Token image” - finished
RULE2 1

“ (add using picture button on top bar) ” } **_(I don't see a picture button but I dragged the pic in)_**

### CODE REVIEW

**Comment by Diggle187** [comment]
please put in a Pull request using the following template 

{ “Name” -  “ ”
“Project Description” -  “ ” 
“Contract” - “ ”
“Symbol” - “ ”
“Website” - “ ”
“Telegram” - “ ”
“Twitter” - “ ”
“Which DEX is your liquidity on” - “ ”
“Token image” - 
“ (add using picture button on top bar) ” }

**Comment by GiverofMemory** [comment]
> please put in a Pull request using the following template
> 
> { “Name” - “ ” “Project Description” - “ ” “Contract” - “ ” “Symbol” - “ ” “Website” - “ ” “Telegram” - “ ” “Twitter” - “ ” “Which DEX is your liquidity on” - “ ” “Token image” - “ (add using picture button on top bar) ” }

Thanks, Updated.

**Comment by Diggle187** [comment]
Next to no liquidity to trade with

**Comment by GiverofMemory** [comment]
> Next to no liquidity to trade with

all of the token supply is added to liquidity.  The price will go up as people buy.  Whether it starts at $1 or $100 doesn't matter, I just want to make it so whales don't have any advantage.

**Comment by Diggle187** [comment]
What’s the token supply and what was initial liquidity?

**Comment by GiverofMemory** [comment]
> What’s the token supply and what was initial liquidity?

The token supply is 1 token.  This is all that will ever exist the ownership has been renounced so no more minting is possible.  There is 18 decimals so the "satoshi's" are 1 quintillion.  It is starting with $1 of BCH so the token price (and marketcap) will start at $1 and we will see where it goes from there.

**Comment by Diggle187** [comment]
Okay, I doubt it will get added with such low liquidity, I’ll help you out a bit and buy/add some liquidity now and see where it goes. Do you plan to have a Telegram channel for it?

**Comment by GiverofMemory** [comment]
> Okay, I doubt it will get added with such low liquidity, I’ll help you out a bit and buy/add some liquidity now and see where it goes. Do you plan to have a Telegram channel for it?

Alright well I have a discord listed, no telegram as I don't have a cell phone.  But sure buy a bit if you want, I don't expect it to get added to default token list very soon, I have TEEF token with $500 in liquidity and it isn't listed on mistswap yet (where that liquidity is).

**Comment by GiverofMemory** [comment]
We are up to about $80 a coin, lets hope we can get listed at $100.

**Comment by GiverofMemory** [comment]
Wow you guys.  I am dumbfounded.  Already the share of the pool was reduced to 50% then 33%.  So even without splitting liquidity to benswap I feel confident that if Tropical ever went down, you guys are providing the liquidity!

So I burned the LP tokens!  Here is proof!  

https://www.smartscan.cash/transaction/0x055b2833fec4e9b4cc58769f565942346d08bd0694480865a18a670a1e53920e

You guys RULE, seriously!

**Comment by Diggle187** [comment]
Okay good step, you can get Telegram on laptop/computer I would suggest doing that to help raise awareness for your projects by creating telegram chats for them. It’s a medium that a lot of the SmartBCH community use

**Comment by GiverofMemory** [comment]
> Okay good step, you can get Telegram on laptop/computer I would suggest doing that to help raise awareness for your projects by creating telegram chats for them. It’s a medium that a lot of the SmartBCH community use

I'll ping the community and see if someone can make one.  Telegram requires a phone number to register even with desktop, I don't have one and even if I did it is a privacy issue.

**Comment by GiverofMemory** [comment]
Ok please add so I don't keep working on this lol.  Picture updated

**Comment by GiverofMemory** [comment]
Liquidity added and now is over 0.5 BCH and the LP tokens have been burned again.

**Comment by GiverofMemory** [comment]
Due to the rules being changed for listing in the middle of me trying to get listed, I am going to close this for now and reconsider my approach.

**Pull request closed without merging**
