### PR TITLE
Adding PENG to tokens.json

### PR DESCRIPTION
**Pull request by jQrgen**
Closes https://github.com/MarketCap-Cash/SmartBCH-Token-List/issues/107

### CODE REVIEW

**Comment by webeli** [comment]
Hi @jQrgen is there liquidity on any DEX?

**Comment by webeli** [comment]
@jQrgen

**Comment by jQrgen** [comment]
Hey @webeli, thanks for the patience over the hollyday.

PENG now has several liquidity pools on mistswap. Following is the welcome message from $PENG telegram group including links to trading pairs with various levels of liquidity on mistswap:


```

[Mistswap: ](https://twitter.com/smaapeng/status/1480686657213014030

$PENG is a artist/fan-token for smaapeng: https://open.spotify.com/artist/0lXRA1R6DcUQG3xI9Pi5T8

Token address
0xA9FFA264fB9ec89cf74B5471AaA80d986c8547F1

BCH/PENG Market 
https://app.mistswap.fi/swap?inputCurrency=BCH&outputCurrency=0xA9FFA264fB9ec89cf74B5471AaA80d986c8547F1

BCH/PENG Chart
https://dexscreener.com/smartbch/0x5a6604e96de87224f8acf52e4ea3cf4428d8bb8f

DONER/PENG Market
https://app.mistswap.fi/swap?inputCurrency=0x14d9337f86d51dcad0d28f6439e00039e251b592&outputCurrency=0xA9FFA264fB9ec89cf74B5471AaA80d986c8547F1

DONER/PENG Chart
https://dexscreener.com/smartbch/0xe50bde3467ca239c46338ff5d47b1bc12333e7d2

PENG/SMART Marked
https://app.mistswap.fi/swap?inputCurrency=0xA9FFA264fB9ec89cf74B5471AaA80d986c8547F1&outputCurrency=0x6e6D4ECE35EEd638A1153339F69E543B7ae5F776

PENG/dSMART Marked
https://app.mistswap.fi/swap?inputCurrency=0xA9FFA264fB9ec89cf74B5471AaA80d986c8547F1&outputCurrency=0x47c259DFe165Cef3e429C9B66bf9ce9dc3e68aC2)
```

**Comment by jQrgen** [comment]
Screenshot 2022-01-11 at 02 24 41

**Comment by webeli** [comment]
@jQrgen great that you have several liquidity pools, but one is enough, our system only pulls data for pools lager than 0.5 BCH. This is a measurement we've done to prevent weird price fluctuation with low liquidity pools.

- Bottom line, please increase atleast one BCH/Token liquidity pool for PENG to minimum 0.5 BCH for our system to pull your token data.

Also this should be done for your DONER token aswell.

**Comment by webeli** [comment]
No updates to latest comment, closing.

**Pull request closed without merging**
