### PR TITLE
Add 🌙🌙🌙🌙

### PR DESCRIPTION
**Pull request by JettScythe**
Image will need to be uploaded

### CODE REVIEW

**Comment by JettScythe** [comment]
Please hold for the image. Getting one designed now.

**Comment by JettScythe** [comment]
logo can be found https://imgur.com/GypGIsZ

**Comment by webeli** [comment]
@JettScythe please add further information, website? social media?

**Comment by JettScythe** [comment]
website: https://www.mmmm.cash/
& is there any way to get the symbol on marketcap.cash to show 🌙🌙🌙🌙 rather than MMMM?

**Pull request merged**
