### PR TITLE
Add SmartDoge (SMART) to tokens.json

### PR DESCRIPTION
**Pull request by smartdogebch**

### CODE REVIEW

**Comment by webeli** [comment]
Hi @smartdogebch is there liquidity on any DEX?

**Comment by smartdogebch** [comment]
Hi @webeli,

There is liquidity - you can find it on mistswap, please see the link provided : https://analytics.mistswap.fi/pairs/0x800632afc31225813b06185ea8be8ed571820a50

**Comment by smartdogebch** [comment]
**Name** - SmartDoge 
**Project Description** - SmartDoge aims to be a token that incentivizes early investors' liquidity mining initiatives and will be an important token playing into the launch of  SmartDEX in the near future which aims to be a first of its kind DEX on SmartBCH, featuring a dynamic reward structure and linear vesting system, acting as a hub for future activities. The token itself is solo-reflectionary with a high % return to the permanently locked liquidity pool creating an ever increasing price floor for early holders.
**Contract** - 0x6e6D4ECE35EEd638A1153339F69E543B7ae5F776
**Symbol** - SMART
**Website** - https://smartdoge.cash
**Telegram** - "https://t.me/smartdogebchofficial
**Twitter** - https://twitter.com/smartdogebch
**Which DEX is your liquidity on?** - Mist Swap (https://analytics.mistswap.fi/pairs/0x800632afc31225813b06185ea8be8ed571820a50)
**Token image** - smartdoge-icon

**Comment by GiverofMemory** [comment]
Eh if dogecoin wants to do a sidechain, which I have reccomended to the devs and they are considering it, I'm sure they can be more creative than calling it "smartdoge" so I don't see too much problem with this.

**Comment by jQrgen** [comment]
Much wow! Very accept merge request.

**Comment by GiverofMemory** [comment]
> Much wow! Very accept merge request.

I agree, if we want this ecosystem to grow we need to be less exclusive and more open to all tokens.

**Comment by jQrgen** [comment]
Much resolve conflict? Does rug pull?

**Pull request merged**
