### PR TITLE
Added website, description and social media

### PR DESCRIPTION
**Pull request by leonidasmark**
Added website, description and social media

### CODE REVIEW

**Review by webeli — APPROVED** [review]

**Comment by webeli** [comment]
Thanks for your PR, your token will be displayed as soon as there's liquidity.

**Comment by webeli** [comment]
@leonidasmark noticed your airdrop, would love some, address: 0xd1023193C32e38feB67404B6308899aC5134bBa4

**Comment by leonidasmark** [comment]
Thank you! Sent!

**Comment by leonidasmark** [comment]
> Thanks for your PR, your token will be displayed as soon as there's liquidity.

We have added liquidity now. Please list our coin if you'd be so kind 🤗

**Pull request merged**
