### PR TITLE
Add Bismuth Win Bi (BWB)

### PR DESCRIPTION
**Pull request by BiWinBi**
Please add new token Bismuth Win Bi (BWB)
If there is anything lost
Please let me know
Thank you very much!

### CODE REVIEW

**Comment by BiWinBi** [comment]
Liquidity added to Mistswap on 11/16
https://analytics.mistswap.fi/pairs/0x692326e3796fb86b293e3c86a7f6d81529e78aa4

**Comment by BiWinBi** [comment]
Liquidity added to Tangoswap on 11/24
https://www.smartscan.cash/transaction/0x2a421e7949c1418643a3fd436270fa9ea869920d62b228675a0633350095d8c2

**Comment by BiWinBi** [comment]
Liquidity added to 1BCH on 11/27

**Comment by webeli** [comment]
Can you rebase this PR on latest main, or create a new PR.

**Comment by BiWinBi** [comment]
> Can you rebase this PR on latest main, or create a new PR.

Sure, I can rebase it right away. Thanks for reminding me of this.

**Pull request closed without merging**
